name: java
visible_name: Java 8 (OpenJDK)
version: "1.8.0_60"
compiler_profile: straitjacket/compiler/java
apparmor_profile: straitjacket/compiled/java
filename: Main.java
docker_image: straitjacket-java

file_extensions:
  - java

tests:
  simple:
    source: |
      import java.io.BufferedReader;
      import java.io.IOException;
      import java.io.InputStreamReader;
      import java.util.ArrayList;
      import java.util.List;

      public class Main {
          public static void main(String[] args) {
              BufferedReader bi = new BufferedReader(new InputStreamReader(System.in));
              String line;
              List<Integer> lines = new ArrayList<>();
              try {
                  while ((line = bi.readLine()) != null) {
                      //put this statement inside of try, in case something other than a number is entered
                      lines.add(Integer.valueOf(line));
                  }
              } catch (IOException | NumberFormatException e) {
              }
              lines
                      .stream()
                      .map(n -> n * 2)
                      .forEach(System.out::println);
          }
    }
    stdin:  "1\n2\n3\n"
    stdout: "\\A2\n4\n6\n\\z"
    stderr:
    exitstatus: 0

  rlimit:
    source: |
      public class Main {
       public static void main(String[] args) {
         int[] data = new int[1073741824];
       }
      }
    stdout: "\\A\\z"
    stderr: "Exception in thread \"main\" java.lang.OutOfMemoryError"
    exitstatus: 1

  apparmor:
    source: |
      import java.nio.file.Files;
      import java.nio.file.Paths;
      import java.util.stream.Stream;

      public class Main {
          public static void main(String[] args) {
              try {
                  Stream<String> lines = Files.lines(Paths.get("/etc/hosts"));
                  lines.forEach(System.out::println);
              } catch (Exception e) {
                  System.err.println("SJ Error: " + e.getMessage());
              }
          }
    }
    stdout: "\\A\\z"
    stderr: 'SJ Error: /etc/hosts \(Permission denied\)'
    exitstatus: 0
